# Generated by Django 6.0.3 on 2026-04-04 14:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('user', '0003_rename_lastname_client_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transferDate', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bankName', models.CharField(max_length=254)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='user.client')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='catalog.producttype')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='user.client')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='catalog.producttype')),
            ],
            options={
                'unique_together': {('client', 'productType')},
            },
        ),
    ]
