# Generated by Django 6.0.3 on 2026-04-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='lastname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
    ]
